sudo: required
services:
- docker
language: node_js
node_js:
- 9.2
script:
- ./nookr_build.sh
- docker tag "nookr-ui:latest" "$REPO/nookr-ui:latest"
- docker tag "nookr-docs:latest" "$REPO/nookr-docs:latest"
- docker tag "nookr-proxy:latest" "$REPO/nookr-proxy:latest"
- docker tag "nookr-api:latest" "$REPO/nookr-api:latest"

after_success:
- docker --version
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- eval $(aws ecr get-login --region ap-southeast-2 --no-include-email)
- docker push "$REPO/nookr-ui:latest"
- docker push "$REPO/nookr-docs:latest"
- docker push "$REPO/nookr-proxy:latest"
- docker push "$REPO/nookr-api:latest"
- ./nookr_deploy.sh