sudo: required
services:
- docker
language: node_js
node_js:
- 9.2
script:
- ./nookr_build.sh
after_success:
- docker --version
- pip install --user awscli
- export PATH=$PATH:$HOME/.local/bin
- eval $(aws ecr get-login --region ap-southeast-2)
- ./nookr_push.sh

