version: '3'
services:
  ui:
    image: nookr_ui_${environment}
    restart: always
    ports:
    - 8081:8080
    networks:
    - nookrnet

  api:
    image: nookr_api_${environment}
    restart: always
    ports:
    - 8082:80
    environment:
      Environment: docker
    networks:
    - nookrnet

  docs:
    image: nookr_docs_${environment}
    restart: always
    ports:
    - 9000:80
    networks:
    - nookrnet

  proxy:
    image: nookr_proxy_${environment}
    restart: always
    ports:
    - 80:80
    networks:
    - nookrnet

networks:
  nookrnet: