version: '3'
services:
  ui:
    image: nookr_ui
    restart: always
    ports:
    - 8081:8080
    networks:
    - nookrnet

  api:
    image: nookr_api
    restart: always
    ports:
    - 8082:80
    environment:
      Environment: docker
    networks:
    - nookrnet

  docs:
    image: nookr_docs
    restart: always
    ports:
    - 9000:80
    networks:
    - nookrnet

  proxy:
    image: nookr_proxy
    restart: always
    ports:
    - 80:80
    depends_on:
    - api
    - ui
    - docs
    networks:
    - nookrnet

networks:
  nookrnet: