version: '3'
services:
  ui:
    image: nginx
    volumes:
    - ./ui:/usr/share/nginx/html:ro
    ports:
    - 8081:80
    networks:
    - nookrnet

  api:
    image: node:carbon
    command: npm run dev
    working_dir: /srv
    ports:
    - 8082:80
    volumes:
    - ./api:/srv
    environment:
      Environment: docker
    networks:
    - nookrnet

  prx:
    image: nginx
    ports:
    - 80:80
    volumes:
    - ./prx/conf.d:/etc/nginx/conf.d
    - ./prx/nginx.conf:/etc/nginx/nginx.conf
    networks:
    - nookrnet

networks:
  nookrnet: