version: '3'
services:
  ui:
    image: node:carbon
    command: npm run dev
    working_dir: /srv
    ports:
    - 8081:8080
    volumes:
    - ./ui:/srv
    networks:
    - nookrnet

  api:
    restart: always
    image: node:carbon
    command: npm run dev
    working_dir: /srv
    ports:
    - 8082:80
    volumes:
    - ./api:/srv
    environment:
      Environment: docker
    networks:
    - nookrnet

  proxy:
    restart: always
    image: nginx
    ports:
    - 80:80
    volumes:
    - ./proxy/conf.d:/etc/nginx/conf.d
    - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
    - nookrnet

networks:
  nookrnet: