---
AWSTemplateFormatVersion: "2010-09-09"
Description: IAM - Roles for AWS services - VPC Flow Logs

Parameters:
  VpcFlowLogsLogGroupName:
    Type: String
    AllowedPattern: '[A-Za-z][A-Za-z0-9-]{0,127}'

Resources:
  PolicyVpcFlowLogs:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: WriteToCloudWatch
      Roles:
      - !Ref RoleVpcFlowLogs
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Action:
          - "logs:DescribeLogGroups"
          - "logs:CreateLogGroup"
          Effect: "Allow"
          Resource:
          - !Sub "arn:aws:logs:*:${AWS::AccountId}:log-group"
          - !Sub "arn:aws:logs:*:${AWS::AccountId}:log-group:*"
        - Action:
          - "logs:CreateLogStream"
          - "logs:PutLogEvents"
          - "logs:DescribeLogStreams"
          Effect: "Allow"
          Resource:
          - !Sub "arn:aws:logs:*:${AWS::AccountId}:log-group:${VpcFlowLogsLogGroupName}"
          - !Sub "arn:aws:logs:*:${AWS::AccountId}:log-group:${VpcFlowLogsLogGroupName}:*"

  RoleVpcFlowLogs:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Principal:
            Service: "vpc-flow-logs.amazonaws.com"
          Action: "sts:AssumeRole"

Outputs:
  RoleVpcFlowLogs:
    Value: !Ref RoleVpcFlowLogs

  RoleVpcFlowLogsArn:
    Value: !GetAtt RoleVpcFlowLogs.Arn
